[project]
name = "seldon"
version = "0.1.0"
description = "Add a short description here"
authors = ["Moritz Sallermann <m.sallermann@fz-juelich.de>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
fmt = "10.1.1.*"