[project]
name = "seldon"
version = "0.1.0"
description = "A code for opinion dynamics simulations."
authors = ["Moritz Sallermann <m.sallermann@fz-juelich.de>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
fmt = "10.1.1.*"